// <auto-generated />
namespace RCTS_Prod.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mig31 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig31));
        
        string IMigrationMetadata.Id
        {
            get { return "201311140440497_mig31"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
