// <auto-generated />
namespace RCTS_Prod.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mig3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig3));
        
        string IMigrationMetadata.Id
        {
            get { return "201311140426417_mig3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
